let currentUser = "Katherine Murr"
let CURRENTUSER = "KATHERINE MURR"
let initial = "K"
let welcomeMessage = "Welcome to Klossybook, " + currentUser + "!"
let excitedWelcomeMessage = "WELCOME TO KLOSSYBOOK, " + CURRENTUSER + "!"
let shortGreeting = "Welcome, " + initial + "!"