let currentUser = "Katherine Murr"
let initial = "K"
let welcomeMessage = "Welcome to Klossybook, " + currentUser + "!"
let excitedWelcomeMessage = "WELCOME TO KLOSSYBOOK, " + currentUser.toUpperCase + "!"
let shortGreeting = "Welcome, " + initial + "!"